POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
    "id": "sdkhjao1iuwhjdn180",
    "username": "Silvio Berlusconi",
    "gender": {
        "id": 1,
        "name": "Maschio"
    }
}

###

POST http://localhost:5000/api/v1/intrested-in
Content-Type: application/json

{
    "user": {
        "id": "21u4ax3hxvenml3p7kdvrjlba"
    },
    "gender": {
        "id": 4
    }
}


###

POST http://localhost:5000/api/v1/user-genres
Content-Type: application/json

{
  "id": [
    "31ypjzitriimy4b2fhfhu5enh4w4"
  ],
  "genres": [
    "italian hip hop",
    "alternative metal",
    "nu metal",
    "rap metal",
    "italian hip hop",
    "italian underground hip hop",
    "rap italiano old school",
    "alternative metal",
    "nu metal",
    "rap metal",
    "rome indie",
    "rome indie",
    "italian hip hop",
    "bedroom pop",
    "indie pop",
    "pop",
    "rome indie",
    "italian hip hop",
    "rap napoletano",
    "bedroom pop",
    "indie pop",
    "pop",
    "rome indie",
    "dance pop",
    "dance pop",
    "edm",
    "electro house",
    "german dance",
    "pop",
    "pop dance",
    "tropical house",
    "uk pop",
    "canadian indie",
    "folk-pop",
    "pop rock",
    "stomp and holler",
    "album rock",
    "glam rock",
    "hard rock",
    "metal",
    "rock",
    "australian rock",
    "hard rock",
    "rock",
    "italian hip hop",
    "rap napoletano",
    "modern rock",
    "rock",
    "italian hip hop",
    "italian underground hip hop",
    "rap italiano old school",
    "italian hip hop",
    "rap napoletano"
  ]
}

###
# Change info about user
PATCH http://localhost:5000/api/v1/users/054tbxkq41y7o0l92jd5nppj4?username=Paolo&genderId=2


###
# Get chats of user
POST http://localhost:5000/api/v1/chat/316wiws546iswu4y6kgtrsf2vky4

###
# Get messages of chat
POST http://localhost:5000/api/v1/messages/1

###
# Update last message
POST http://localhost:5000/api/v1/chat/update-last-message?chatId=1&lastMessage=fsdfa&lastTimeSent=2022-10-05 21:16:45.000000

###
# Add message
POST http://localhost:5000/api/v1/messages/add-message?chatId=1&senderId=316wiws546iswu4y6kgtrsf2vky4&text=test_url_query&dateTime=2022-10-05 21:16:45.000000