POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
    "id": "sdkhjao1iuwhjdn180",
    "username": "Silvio Berlusconi",
    "gender": {
        "id": 1,
        "name": "Maschio"
    }
}

###

POST http://localhost:5000/api/v1/intrested-in
Content-Type: application/json

{
    "user": {
        "id": "21u4ax3hxvenml3p7kdvrjlba"
    },
    "gender": {
        "id": 4
    }
}


###
# ADD LISTENED GENRES
POST http://localhost:5000/api/v1/users-genres
Content-Type: application/json

{
  "id": [
    "31ypjzitriimy4b2fhfhu5enh4w4"
  ],
  "genres": [
    "italian hip hop",
    "alternative metal",
    "nu metal",
    "rap metal",
    "italian hip hop",
    "italian underground hip hop",
    "rap italiano old school",
    "alternative metal",
    "nu metal",
    "rap metal",
    "rome indie",
    "rome indie",
    "italian hip hop",
    "bedroom pop",
    "indie pop",
    "pop",
    "rome indie",
    "italian hip hop",
    "rap napoletano",
    "bedroom pop",
    "indie pop",
    "pop",
    "rome indie",
    "dance pop",
    "dance pop",
    "edm",
    "electro house",
    "german dance",
    "pop",
    "pop dance",
    "tropical house",
    "uk pop",
    "canadian indie",
    "folk-pop",
    "pop rock",
    "stomp and holler",
    "album rock",
    "glam rock",
    "hard rock",
    "metal",
    "rock",
    "australian rock",
    "hard rock",
    "rock",
    "italian hip hop",
    "rap napoletano",
    "modern rock",
    "rock",
    "italian hip hop",
    "italian underground hip hop",
    "rap italiano old school",
    "italian hip hop",
    "rap napoletano"
  ]
}

###
# ADD TOP ARTISTS
POST http://localhost:5000/api/v1/users-artists
Content-Type: application/json

{
  "id": [
    "31ypjzitriimy4b2fhfhu5enh4w4"
  ],
  "artists": [
    "artista",
    "artista1",
    "artista2",
    "artista3",
    "artista4"
  ]
}

###
# ADD TOP SONGS
POST http://localhost:5000/api/v1/users-songs
Content-Type: application/json

{
  "id": [
    "31ypjzitriimy4b2fhfhu5enh4w4"
  ],
  "songs": [
    "canzone",
    "canzone1",
    "canzone2",
    "canzone3",
    "canzone4"
  ]
}


###
# Change info about user
PATCH http://localhost:5000/api/v1/users/054tbxkq41y7o0l92jd5nppj4?username=Paolo&genderId=2




### MESSAGING TESTING

### CREATE A CHAT
POST http://localhost:5000/api/v1/chat/add-chat
Content-Type: application/json

{
  "user1Id": "3hgt4v55jcdgkiaygsy1naiui", 
  "user2Id": "3klicvqktp0kxiqr690pb1923"
}

### GET USER'S CHAT
GET http://localhost:5000/api/v1/chat/4nll1r1xyxfuf6p66jhfyo385


### ADD A MESSAGE
POST http://localhost:5000/api/v1/messages/add-message
Content-Type: application/json

{
  "chatId": 506,
  "senderId": "3hgt4v55jcdgkiaygsy1naiui",
  "text": "Carlo",
  "dateTime": "{{$datetime rfc1123}}"
}

### GET CHAT MESSAGES
GET http://localhost:5000/api/v1/messages/506
