POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
    "id": "sdkhjao1iuwhjdn180",
    "username": "Silvio Berlusconi",
    "gender": {
        "id": 1,
        "name": "Maschio"
    }
}

###

POST http://localhost:5000/api/v1/intrested-in
Content-Type: application/json

{
    "user": {
        "id": "21u4ax3hxvenml3p7kdvrjlba"
    },
    "gender": {
        "id": 4
    }
}